description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "explode"
publish_to: "none"
dependencies: 
  angel_configuration: "^1.1.0"
  angel_model: "^1.0.0"
  angel_serialize: "^1.0.0-alpha"
  angel_websocket: "^1.1.0"
dev_dependencies: 
  angel_serialize_generator: "^1.0.0-alpha"
  browser: "^0.10.0"
  build_runner: "^0.5.0"
  dart_to_js_script_rewriter: "^1.0.0"
  grinder: "^0.8.0+2"
  http: "^0.11.3"
  test: "^0.12.13"
environment: 
  sdk: ">=1.19.0"
transformers: 
  - "dart_to_js_script_rewriter"
